function OFDMToolGUI()
    % OFDMToolGUI - A graphical user interface for OFDM Received Signal Analysis Tool.

    existingFig = findall(0, 'Type', 'figure', 'Name', 'OFDM Received Signal Analysis Tool');
    if ~isempty(existingFig)
        close(existingFig);
    end

    fig = uifigure('Name', 'OFDM Received Signal Analysis Tool', ...
        'Position', [100, 100, 600, 600]);

    uilabel(fig, 'Text', 'OFDM Received Signal Analysis Tool', ...
        'Position', [150, 550, 300, 40], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center');

    %% File Path Section
    uilabel(fig, 'Text', 'Signal File Path:', ...
        'Position', [50, 500, 150, 22], ...
        'FontSize', 12);

    filePath = uieditfield(fig, 'text', ...
        'Position', [260, 500, 260, 22]);

    uibutton(fig, 'Text', 'Browse', ...
        'Position', [460, 500, 100, 22], ...
        'ButtonPushedFcn', @(btn, event) browseFile(filePath));

    %% General Parameters
    uilabel(fig, 'Text', 'Sampling Rate (Hz):', ...
        'Position', [50, 450, 150, 22], ...
        'FontSize', 12);

    fsInput = uieditfield(fig, 'numeric', ...
        'Position', [260, 450, 100, 22], ...
        'Value', 7e6);

    uilabel(fig, 'Text', 'Transform Type:', ...
        'Position', [50, 410, 150, 22], ...
        'FontSize', 12);

    transformTypeInput = uidropdown(fig, ...
        'Items', {'fft-double', 'fft-single'}, ...
        'Position', [260, 410, 150, 22], ...
        'Value', 'fft-double');

    uilabel(fig, 'Text', 'Enable Plotting:', ...
        'Position', [50, 370, 150, 22], ...
        'FontSize', 12);

    plotFlagInput = uicheckbox(fig, ...
        'Text', '', ...
        'Position', [260, 370, 22, 22], ...
        'Value', true);

    uilabel(fig, 'Text', 'Subcarrier Estimation Method:', ...
        'Position', [50, 330, 200, 22], ...
        'FontSize', 12);

    scparamInput = uidropdown(fig, ...
        'Items', {'mean', 'kmeans'}, ...
        'Position', [260, 330, 150, 22], ...
        'Value', 'mean');

    %% Bandwidth Estimation
    uilabel(fig, 'Text', 'Bandwidth Type:', ...
        'Position', [50, 290, 150, 22], ...
        'FontSize', 12);

    bwTypeInput = uidropdown(fig, ...
        'Items', {'3dB', 'threshold', 'OBW'}, ...
        'Position', [260, 290, 150, 22], ...
        'Value', '3dB');

    uilabel(fig, 'Text', 'Threshold Factor:', ...
        'Position', [50, 250, 200, 22], ...
        'FontSize', 12);

    thresholdFactorInput = uieditfield(fig, 'text', ...
        'Position', [260, 250, 100, 22], ...
        'Value', '', ...
        'Tooltip', 'Required only for threshold bandwidth mode');

    %% Autocorrelation Analysis
    uilabel(fig, 'Text', 'Peak Threshold (AutoCorr):', ...
        'Position', [50, 210, 200, 22], ...
        'FontSize', 12);

    peakThresholdInput = uieditfield(fig, 'numeric', ...
        'Position', [260, 210, 100, 22], ...
        'Value', 0.065);

    %% Detection Parameters
    uilabel(fig, 'Text', 'Detection Type:', ...
        'Position', [50, 170, 150, 22], ...
        'FontSize', 12);

    detectionTypeInput = uidropdown(fig, ...
        'Items', {'hard', 'soft'}, ...
        'Position', [260, 170, 150, 22], ...
        'Value', 'hard');

    uilabel(fig, 'Text', 'Phase Offset:', ...
        'Position', [50, 130, 150, 22], ...
        'FontSize', 12);

    phaseOffsetInput = uieditfield(fig, 'numeric', ...
        'Position', [260, 130, 100, 22], ...
        'Value', 0);

    uilabel(fig, 'Text', 'Symbol Order:', ...
        'Position', [50, 90, 150, 22], ...
        'FontSize', 12);

    symOrderInput = uidropdown(fig, ...
        'Items', {'natural', 'gray'}, ...
        'Position', [260, 90, 150, 22], ...
        'Value', 'natural');

    uibutton(fig, 'Text', 'Start Simulation', ...
        'Position', [260, 30, 150, 40], ...
        'ButtonPushedFcn', @(btn, event) startSimulation());

    function browseFile(fileField)
        [file, path] = uigetfile('*.mat', 'Select the Received Signal File');
        if isequal(file, 0)
            return;
        end
        fileField.Value = fullfile(path, file);
    end

    function startSimulation()
        if isempty(filePath.Value) || exist(filePath.Value, 'file') ~= 2
            uialert(fig, 'Invalid file path. Please select a valid MAT file.', 'File Error');
            return;
        end

        try
            loadedData = load(filePath.Value, 'RxSignal');
            RxSignal = loadedData.RxSignal;
        catch
            uialert(fig, 'Unable to load RxSignal from the selected file.', 'File Error');
            return;
        end

        param.fs = fsInput.Value;
        param.transformType = transformTypeInput.Value;
        param.plotFlag = plotFlagInput.Value;
        param.scmethod = scparamInput.Value;
        param.bwType = bwTypeInput.Value;
        param.peakThreshold = peakThresholdInput.Value;
        param.softFlag = detectionTypeInput.Value;
        param.phaseOff = phaseOffsetInput.Value;
        param.symOrder = symOrderInput.Value;

        if isempty(thresholdFactorInput.Value)
            param.thresholdFactor = [];
        else
            param.thresholdFactor = str2double(thresholdFactorInput.Value);

            if isnan(param.thresholdFactor) || param.thresholdFactor <= 0
                uialert(fig, 'Threshold factor must be a positive numeric value.', 'Input Error');
                return;
            end
        end

        try
            [results, param] = main(RxSignal, param);

            resultMessage = sprintf(['Simulation completed successfully!\n\n' ...
                'Estimated SNR: %.2f dB\n' ...
                'Modulation Type: %s\n' ...
                'Modulation Order: %d'], ...
                results.snrdB, results.modType, results.modOrder);

            uialert(fig, resultMessage, 'Simulation Results');

            [saveFile, savePath] = uiputfile('results.mat', 'Save Results As');
            if ~isequal(saveFile, 0)
                save(fullfile(savePath, saveFile), 'results', 'param');
            end

        catch ME
            uialert(fig, sprintf('Error during simulation:\n%s', ME.message), 'Simulation Error');
        end
    end
end
